using SourcingEngine.Common.Models;

namespace SourcingEngine.Core.Services;

/// <summary>
/// Result from LLM enrichment of embedding text.
/// Contains fluent, natural-language description and enrichment paragraphs
/// generated by the LLM for optimal embedding quality.
/// </summary>
public class EnrichedEmbeddingText
{
    /// <summary>
    /// A concise, fluent one-sentence description of the product or BOM item.
    /// Includes the name and primary UOM/dimensions in natural language.
    /// Example: "8-inch standard weight concrete masonry block for load-bearing wall construction"
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Structured technical specifications as a list of name/value/uom items.
    /// Serialized as a JSON array in the embedding text:
    /// [{"name":"width","value":290,"uom":"mm"},{"name":"ssg available","value":true,"uom":null}]
    /// Both products and BOM items use the same structure.
    /// </summary>
    public List<TechnicalSpecItem> TechnicalSpecs { get; set; } = new();

    /// <summary>
    /// A concise enrichment paragraph aggregating vendor context, material family,
    /// use cases, avoidance guidance, finishes, and any other available knowledge.
    /// Written in natural, fluent language for optimal embedding quality.
    /// </summary>
    public string Enrichment { get; set; } = string.Empty;
}

/// <summary>
/// Enriches embedding text by calling an LLM to produce fluent, natural-language
/// [DESCRIPTION] and [PRODUCTENRICHMENT] sections from raw product/BOM data.
/// Used by both <see cref="ProductEmbeddingTextBuilder"/> (batch) and
/// <see cref="QueryEmbeddingTextBuilder"/> (runtime) to improve embedding quality.
/// </summary>
public interface IEmbeddingTextEnricher
{
    /// <summary>
    /// Enrich a product's raw data into fluent description and enrichment text.
    /// Called at embedding generation time (batch) and the result is stored.
    /// </summary>
    /// <param name="product">Raw product data including vendor, family, specs, knowledge</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>LLM-generated fluent text for [DESCRIPTION] and [PRODUCTENRICHMENT]</returns>
    Task<EnrichedEmbeddingText> EnrichProductTextAsync(
        ProductEmbeddingInput product,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Enrich a BOM line item's raw data into fluent description and enrichment text.
    /// Called at search time (runtime) for each BOM item before embedding.
    /// </summary>
    /// <param name="bomItem">The BOM line item with description, specs, certifications, additional data</param>
    /// <param name="parsedQuery">LLM-parsed query data (search query with synonyms, attributes, family)</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>LLM-generated fluent text for [DESCRIPTION] and [PRODUCTENRICHMENT]</returns>
    Task<EnrichedEmbeddingText> EnrichBomItemTextAsync(
        Common.Models.BomLineItem bomItem,
        ParsedBomQuery parsedQuery,
        CancellationToken cancellationToken = default);
}
